POST http://localhost:4000/api/v1/register HTTP/1.1
Content-Type: application/json

    {
    "name":"nico",
    "username":"nico123",
    "email":"nicolas@gmail.com",
    "password":"nksjfh872"
    }
###
GET http://localhost:4000/api/v1/users HTTP/1.1

###
PUT http://localhost:4000/api/v1/users/1 HTTP/1.1   
Content-Type: application/json

###
GET http://localhost:4000/api/v1/roles/689be5d3ff93cffc038abb92

###
PUT  http://localhost:4000/api/v1/users/689a9655880cddee0af4f93d HTTP/1.1
Content-Type: application/json

    {
    "name":"John Updated",
    "username":"johnUpdated",
    "email":"emailupdate@gmail.com"
    }

###
DELETE http://localhost:4000/api/v1/users/689a9655880cddee0af4f93d HTTP/1.1